name: build
run-name: ${{ inputs.wheel }}

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'list of platforms to build for'
        type: string
        required: false
        default: "amd64,arm64,arm/v7"

      python:
        description: 'list of python versions MAJOR.MINOR to build for'
        type: string
        required: false
        default: "3.13,3.12"

      wheel:
        description: 'name of wheel to use for build'
        type: string
        required: true

      version:
        description: 'version of wheel to build'
        type: string
        required: true

jobs:
  # ╔═════════════════════════════════════════════════════╗
  # ║                                                     ║
  # ║                                                     ║
  # ║               CREATE PLATFORM MATRIX                ║
  # ║                                                     ║
  # ║                                                     ║
  # ╚═════════════════════════════════════════════════════╝
  matrix:
    runs-on: ubuntu-latest
    outputs:
      stringify: ${{ steps.setup-matrix.outputs.stringify }}

    steps:
      - name: matrix / setup list
        id: setup-matrix
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const platforms = "${{ github.event.inputs.platform }}".split(",");
            const pythons = "${{ github.event.inputs.python }}".split(",");
            const matrix = {include:[]};
            for(const platform of platforms){
              for(const python of pythons){
                switch(platform){
                  case "amd64": matrix.include.push({python:python, platform:platform, runner:"ubuntu-24.04"}); break;
                  case "arm64": matrix.include.push({python:python, platform:platform, runner:"ubuntu-24.04-arm"}); break;
                  case "arm/v7": matrix.include.push({python:python, platform:platform, runner:"ubuntu-24.04-arm"}); break;
                }
              }
            }
            const stringify = JSON.stringify(matrix);
            core.setOutput('stringify', stringify);

  # ╔═════════════════════════════════════════════════════╗
  # ║                                                     ║
  # ║                                                     ║
  # ║                    BUILD WHEEL                      ║
  # ║                                                     ║
  # ║                                                     ║
  # ╚═════════════════════════════════════════════════════╝
  build:
    needs: matrix
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix.outputs.stringify) }}

    steps:
      # CHECKOUT REPO
      - name: init / checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # SETUP ENVIRONMENT
      - name: init / environment
        run: |
          echo "MATRIX_PLATFORM_SANITIZED=$(echo ${{ matrix.platform }} | sed 's#/##')" >> "${GITHUB_ENV}"

      # SETUP QEMU
      - name: init / setup qemu
        if: matrix.platform == 'arm/v7'
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          image: tonistiigi/binfmt
          cache-image: false

      # SETUP BUILDX BUILDER WITH USING LOCAL REGISTRY TO STORE IMAGE
      - name: init / setup buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          driver-opts: network=host

      # BUILD WHEEL INSIDE CONTAINER
      - name: wheel / build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ${{ github.event.inputs.wheel }}.dockerfile
          platforms: linux/${{ matrix.platform }}
          tags: wheel
          outputs: type=docker,dest=${{ runner.temp }}/${{ github.event.inputs.wheel }}.${{ matrix.python }}.${{ env.MATRIX_PLATFORM_SANITIZED }}.tar
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
            WHEEL_VERSION=${{ github.event.inputs.version }}

      # SAVE IMAGE IN ARTIFACT CACHE
      - name: artifact / save image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.wheel }}.${{ matrix.python }}.${{ env.MATRIX_PLATFORM_SANITIZED }}
          path: ${{ runner.temp }}/${{ github.event.inputs.wheel }}.${{ matrix.python }}.${{ env.MATRIX_PLATFORM_SANITIZED }}.tar
          retention-days: 1


  # ╔═════════════════════════════════════════════════════╗
  # ║                                                     ║
  # ║                                                     ║
  # ║                   EXTRACT WHEEL                     ║
  # ║                                                     ║
  # ║                                                     ║
  # ╚═════════════════════════════════════════════════════╝
  extract:
    needs: 
      - build
      - matrix
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix.outputs.stringify) }}

    permissions:
      contents: write

    steps:
      # SETUP ENVIRONMENT
      - name: init / environment
        run: |
          echo "MATRIX_PLATFORM_SANITIZED=$(echo ${{ matrix.platform }} | sed 's#/##')" >> "${GITHUB_ENV}"
          mkdir -p ${{ runner.temp }}/whl

      # GET IMAGE FROM ARTIFACT CACHE
      - name: artifact / load image
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.wheel }}.${{ matrix.python }}.${{ env.MATRIX_PLATFORM_SANITIZED }}
          path: ${{ runner.temp }}

      # EXTRACT WHEEL FROM CONTAINER IMAGE
      - name: extract / wheel
        run: |
          docker load --input ${{ runner.temp }}/${{ github.event.inputs.wheel }}.${{ matrix.python }}.${{ env.MATRIX_PLATFORM_SANITIZED }}.tar
          docker run --rm -v ${{ runner.temp }}/whl:/whl wheel

      # FIX SEMVER ISSUES
      - name: extract / fix semver
        run: |
          cd ${{ runner.temp }}/whl/
          for WHL in *; do
            if echo "${WHL}" | grep -q "0.0.0"; then
              WHL_NEW=$(echo "${WHL}" | sed 's/0.0.0/'${{ github.event.inputs.version }}'/')
              echo "renaming ${WHL} to ${WHL_NEW}"
              mv ${WHL} ${WHL_NEW}
            fi
          done

      # SAVE WHEEL IN ARTIFACT
      - name: artifact / save wheel
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.wheel }}.whl.${{ matrix.python }}.${{ env.MATRIX_PLATFORM_SANITIZED }}
          path: ${{ runner.temp }}/whl
          retention-days: 1

  # ╔═════════════════════════════════════════════════════╗
  # ║                                                     ║
  # ║                                                     ║
  # ║                    PUSH WHEELS                      ║
  # ║                                                     ║
  # ║                                                     ║
  # ╚═════════════════════════════════════════════════════╝
  push:
    needs: extract
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # CHECKOUT REPO
      - name: init / checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # SAVE WHEEL IN ARTIFACT
      - name: artifact / load wheels
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/whl
          pattern: ${{ github.event.inputs.wheel }}.whl*
          merge-multiple: true

      # GIT PUSH ALL WHEELS AT ONCE
      - name: git / push
        run: |
          mkdir -p ./whl/${{ github.event.inputs.wheel }}
          cp -af ${{ runner.temp }}/whl/. ./whl/${{ github.event.inputs.wheel }}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: add ${{ github.event.inputs.wheel }} ${{ github.event.inputs.version }}"
          git push

      # CREATE RELEASE FOR WHEELS
      - name: git / release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.wheel }}-${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.wheel }} ${{ github.event.inputs.version }}
          files: |
            ./whl/${{ github.event.inputs.wheel }}/*

      # CREATE WHEEL LINKS
      - name: html / wheel
        continue-on-error: true
        run: |
          cd ./whl/${{ github.event.inputs.wheel }}
          echo "" > ./${{ github.event.inputs.wheel }}.html
          for WHL in *.whl; do
            echo "<a href='https://github.com/11notes/python-wheels/releases/download/${{ github.event.inputs.wheel }}-${{ github.event.inputs.version }}/${WHL}'>${WHL}</a><br />" >> ./${{ github.event.inputs.wheel }}.html
          done
          git add ./${{ github.event.inputs.wheel }}.html
          git commit -m "chore: update ${{ github.event.inputs.wheel }}.html"
          git push

      # CREATE INDEX
      - name: html / index
        uses: the-actions-org/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7 # v4.0.0
        with:
          wait-for-completion: false
          workflow: index.yml
          token: "${{ secrets.REPOSITORY_TOKEN }}"