name: fnv-hash-fast

on:
  workflow_dispatch:
    inputs:
      version:
        description: "set semver for build"
        type: string
        required: false
        default: "null"
  schedule:
    - cron: "18 8 * * *"

jobs:
  fnv-hash-fast:
    runs-on: ubuntu-latest

    steps:
      - name: udpate / get latest version
        run: |
          if [ "${{ github.event.inputs.version }}" != "null" ] && [ "${{ github.event.inputs.version }}" != "" ]; then
            echo "LATEST=${{ github.event.inputs.version }}" >> "${GITHUB_ENV}"
          else
            echo "LATEST=$(curl -s https://api.github.com/repos/Bluetooth-Devices/fnv-hash-fast/releases/latest | jq -r '.tag_name' | sed 's/v//')" >> "${GITHUB_ENV}"
          fi

      - name: udpate / call update workflow
        if: env.LATEST != 'null' && env.LATEST != ''
        uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4 # v1.3.1 # v4.0.0
        with:
          wait-for-completion: false
          workflow: update.yml
          token: "${{ secrets.REPOSITORY_TOKEN }}"
          inputs: '{ "wheel":"fnv-hash-fast", "version":"${{ env.LATEST }}" }'