name: sgmllib3k

on:
  workflow_dispatch:
    inputs:
      version:
        description: "set semver for build"
        type: string
        required: false
        default: "null"
  schedule:
    - cron: "18 14 * * *"

jobs:
  sgmllib3k:
    runs-on: ubuntu-latest

    steps:
      - name: udpate / get latest version
        run: |
          echo "LATEST=latest" >> "${GITHUB_ENV}"

      - name: udpate / call update workflow
        if: env.LATEST != 'null' && env.LATEST != ''
        uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4 #v1.3.1 # v4.0.0
        with:
          wait-for-completion: false
          workflow: update.yml
          token: "${{ secrets.REPOSITORY_TOKEN }}"
          inputs: '{ "wheel":"sgmllib3k", "version":"${{ env.LATEST }}", "python":"3.14", "platform":"amd64" }'